version: "3"

services:
    user-emu:
        container_name: vivotek-user
        build:
          context: .
          dockerfile: ./user-emu/Dockerfile
        ports:
          - "1234:80"
        privileged: true
