version: "3"

services:
    system-emu:
        container_name: cisco-system
        build:
            context: .
            dockerfile: ./system-emu/Dockerfile
        privileged: true
        ports:
            - "8888:80"
            - "6666:6666"
